/* Products Database for Royal Affair - Designer Suits */
/* All images from assets/images are properly categorized and assigned */

const products = [

  /* =========================================================
     CATEGORY: Salwar Kameez
  ========================================================= */
  {
    id: 1,
    name: "Noor Ivory Embroidered Pakistani Suit",
    slug: "noor-ivory-embroidered-pakistani-suit",
    category: "Salwar Kameez",
    subcategory: "Pakistani Suits",
    tags: ["pakistani", "ivory", "embroidered", "lawn", "wedding"],
    shortDescription: "Traditional ivory straight salwar kameez with delicate floral Aari crewel embroidery on chiffon.",
    fullDescription: "Celebrate heritage craftsmanship with the Noor Pakistani Suit. Featuring premium chiffon fabric with all-over silver and white lace embroidery on the bodice and sleeves, matched with a matching sharara and sheer dupatta. Perfect for nikahs and formal occasions.",
    price: 4899,
    originalPrice: 5499,
    discount: 10,
    rating: 4.8,
    reviewCount: 22,
    sku: "RA-NOOR-PK01",
    stock: 25,
    images: ["./assets/images/image copy.png", "./assets/images/image copy.png"],
    colors: ["Ivory", "Soft Pink"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Chiffon & Lace",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 2,
    name: "Riwaayat Ivory Gold Salwar Suit",
    slug: "riwaayat-ivory-gold-salwar-suit",
    category: "Salwar Kameez",
    subcategory: "Silk Suits",
    tags: ["ivory", "gold", "silk", "festive", "salwar kameez"],
    shortDescription: "Ivory straight-cut kameez with intricate gold zari embroidery and dupatta.",
    fullDescription: "A classic minimalist design for elegant gatherings. The Riwaayat Kurta features premium raw silk weave in soft ivory, detailed with scalloped gold zardozi motifs along the hem and neckline, paired with straight pants and a handloom dupatta.",
    price: 5299,
    originalPrice: 5999,
    discount: 11,
    rating: 4.7,
    reviewCount: 29,
    sku: "RA-RIW-SL02",
    stock: 20,
    images: ["./assets/images/image copy 2.png", "./assets/images/image copy 2.png"],
    colors: ["Ivory", "Gold"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Raw Silk",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: true
  },
  {
    id: 3,
    name: "Meher Ivory Organza Suit Set",
    slug: "meher-ivory-organza-suit-set",
    category: "Salwar Kameez",
    subcategory: "Organza Suits",
    tags: ["organza", "ivory", "festive", "embroidered"],
    shortDescription: "Elegant ivory organza straight kameez with gold sequin detailing and wide dupatta.",
    fullDescription: "A breathtaking piece, the Meher Organza Set features a lightweight ivory organza kameez with gold sequin embroidery on the bodice panel. Includes straight pants and a sheer organza dupatta. Ideal for mehndi and engagement celebrations.",
    price: 6499,
    originalPrice: 7199,
    discount: 9,
    rating: 4.6,
    reviewCount: 17,
    sku: "RA-MEH-OR03",
    stock: 18,
    images: ["./assets/images/image copy 3.png", "./assets/images/image copy 3.png"],
    colors: ["Ivory", "Peach"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Organza & Georgette",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: false,
    newArrival: true
  },
  {
    id: 4,
    name: "Zoya Beige Anarkali Kurta Set",
    slug: "zoya-beige-anarkali-kurta-set",
    category: "Salwar Kameez",
    subcategory: "Lawn",
    tags: ["beige", "pink dupatta", "casual", "kurta", "festive"],
    shortDescription: "Breezy beige A-line kurta with a pop of deep pink dupatta and golden embroidery neckline.",
    fullDescription: "Stay comfortable and stylish in the Zoya Beige Kurta Set. Features a relaxed beige A-line kameez with gold embroidery at the yoke, paired with matching trousers and a vibrant deep pink printed dupatta. Perfect for daytime events.",
    price: 2999,
    originalPrice: 3499,
    discount: 14,
    rating: 4.5,
    reviewCount: 40,
    sku: "RA-ZOY-BG04",
    stock: 35,
    images: ["./assets/images/image copy 4.png", "./assets/images/image copy 4.png"],
    colors: ["Beige", "Pink"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Cotton Lawn",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: false,
    newArrival: true
  },
  {
    id: 5,
    name: "Inayat Lavender Pakistani Suit",
    slug: "inayat-lavender-pakistani-suit",
    category: "Salwar Kameez",
    subcategory: "Pakistani Suits",
    tags: ["lavender", "pakistani", "chiffon", "embroidered", "wedding"],
    shortDescription: "Dreamy lavender chiffon Pakistani straight suit with silver sequin embroidery.",
    fullDescription: "Make a gentle statement in our Inayat Lavender Suit. Crafted from sheer lavender chiffon with all-over silver resham thread and sequin-embroidered panels. Set includes matching straight salwar and a flowing dupatta.",
    price: 4499,
    originalPrice: 4999,
    discount: 10,
    rating: 4.7,
    reviewCount: 14,
    sku: "RA-INA-LV05",
    stock: 15,
    images: ["./assets/images/image copy 5.png", "./assets/images/image copy 5.png"],
    colors: ["Lavender"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Chiffon & Net",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: true
  },
  {
    id: 6,
    name: "Aafreen Pink Sharara Salwar Set",
    slug: "aafreen-pink-sharara-salwar-set",
    category: "Salwar Kameez",
    subcategory: "Silk Suits",
    tags: ["pink", "organza", "sharara", "casual", "modern"],
    shortDescription: "Soft pink organza kameez with palazzo-style pants and matching chiffon dupatta.",
    fullDescription: "The Aafreen Pink Suit brings modern simplicity to ethnic fashion. A soft blush pink raw silk straight kameez with subtle V-neckline, paired with wide-leg pants and a sheer pink chiffon dupatta. Great for intimate gatherings.",
    price: 3799,
    originalPrice: 3999,
    discount: 5,
    rating: 4.6,
    reviewCount: 31,
    sku: "RA-AAF-PK06",
    stock: 22,
    images: ["./assets/images/image copy 6.png", "./assets/images/image copy 6.png"],
    colors: ["Blush Pink"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Raw Silk & Organza",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 7,
    name: "Gulnaar Grey Mirror Work Suit",
    slug: "gulnaar-grey-mirror-work-suit",
    category: "Salwar Kameez",
    subcategory: "Georgette Suits",
    tags: ["grey", "mirror work", "georgette", "festive", "embroidered"],
    shortDescription: "Steel grey georgette straight suit with hand-stitched mirror embroidery and blue dupatta.",
    fullDescription: "Reflect elegance at your next celebration. The Gulnaar Grey Suit features a premium georgette kameez with extensive hand-stitched mirror and sequin work across the bodice and sleeve hem, paired with a richly embroidered navy dupatta.",
    price: 6899,
    originalPrice: 7499,
    discount: 8,
    rating: 4.8,
    reviewCount: 19,
    sku: "RA-GUL-GR07",
    stock: 10,
    images: ["./assets/images/image copy 7.png", "./assets/images/image copy 7.png"],
    colors: ["Grey", "Steel Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Georgette",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 8,
    name: "Mahira Black Straight Kurta Set",
    slug: "mahira-black-straight-kurta-set",
    category: "Salwar Kameez",
    subcategory: "Silk Suits",
    tags: ["black", "minimal", "modern", "straight kurta", "casual"],
    shortDescription: "Sleek black straight kurta with printed organza dupatta for a bold, modern look.",
    fullDescription: "Make a powerful statement with the Mahira Black Kurta Set. A beautifully tailored black crepe straight kurta with subtle hemline scallop detailing, paired with black cigarette trousers and a sheer printed organza dupatta.",
    price: 3499,
    originalPrice: 3999,
    discount: 12,
    rating: 4.5,
    reviewCount: 26,
    sku: "RA-MAH-BK08",
    stock: 28,
    images: ["./assets/images/image copy 14.png", "./assets/images/image copy 14.png"],
    colors: ["Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: "Crepe & Organza",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: false,
    newArrival: true
  },
  {
    id: 9,
    name: "Naaz Brown Georgette Pakistani Suit",
    slug: "naaz-brown-georgette-pakistani-suit",
    category: "Salwar Kameez",
    subcategory: "Pakistani Suits",
    tags: ["brown", "georgette", "lace", "pakistani", "festive"],
    shortDescription: "Mocha brown georgette Pakistani suit with white lace appliqué and balloon sleeves.",
    fullDescription: "Effortlessly chic, the Naaz Brown Suit is crafted from premium georgette in warm mocha, adorned with delicate white floral lace appliqué on the bodice and balloon sleeves. A contemporary Pakistani silhouette for modern women.",
    price: 4299,
    originalPrice: 4799,
    discount: 10,
    rating: 4.6,
    reviewCount: 33,
    sku: "RA-NAA-BR09",
    stock: 16,
    images: ["./assets/images/image copy 9.png", "./assets/images/image copy 9.png"],
    colors: ["Mocha Brown"],
    sizes: ["M", "L", "XL"],
    fabric: "Georgette",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 10,
    name: "Rani Pink Embroidered Kurta Set",
    slug: "rani-pink-embroidered-kurta-set",
    category: "Salwar Kameez",
    subcategory: "Silk Suits",
    tags: ["magenta", "rani pink", "silk", "embroidered", "festive"],
    shortDescription: "Vibrant rani pink silk short kurta with heavy resham embroidery and matching palazzo.",
    fullDescription: "Dazzle at every event with the Rani Pink Kurta Set. A richly embroidered short-length silk kurta in deep magenta with thread and sequin work at the neck and sleeves, paired with matching palazzo pants.",
    price: 3999,
    originalPrice: 4499,
    discount: 11,
    rating: 4.7,
    reviewCount: 21,
    sku: "RA-RNP-PK10",
    stock: 20,
    images: ["./assets/images/image copy 18.png", "./assets/images/image copy 18.png"],
    colors: ["Rani Pink", "Magenta"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Silk",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 11,
    name: "Zara Sky Blue Lawn Pakistani Suit",
    slug: "zara-sky-blue-lawn-pakistani-suit",
    category: "Salwar Kameez",
    subcategory: "Lawn",
    tags: ["sky blue", "lawn", "pakistani", "summer", "floral"],
    shortDescription: "Fresh sky blue cotton lawn Pakistani suit with floral prints and colorful dupatta.",
    fullDescription: "Celebrate summer festivities with the Zara Sky Blue Lawn Suit. Features a breathable cotton lawn kameez with floral embroidered patches and lace trims, paired with cigarette pants and a vibrant multi-colored printed dupatta.",
    price: 2799,
    originalPrice: 2999,
    discount: 6,
    rating: 4.5,
    reviewCount: 44,
    sku: "RA-ZAR-SB11",
    stock: 40,
    images: ["./assets/images/image.png", "./assets/images/image.png"],
    colors: ["Sky Blue", "White"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Cotton Lawn",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: false,
    newArrival: true
  },

  /* =========================================================
     CATEGORY: Anarkali
  ========================================================= */
  {
    id: 12,
    name: "Meher Festive Maroon Anarkali",
    slug: "meher-festive-maroon-anarkali",
    category: "Anarkali",
    subcategory: "Velvet Suits",
    tags: ["maroon", "velvet", "anarkali", "wedding", "zardozi"],
    shortDescription: "Premium velvet deep maroon Anarkali set with gold zardozi paneling.",
    fullDescription: "A statement design from our festive wardrobes, the Meher Anarkali features structured paneling cut from high-quality velvet, detailed with hand-applied gold sequins along the borders. Set includes churidar pants and a Banarasi dupatta.",
    price: 12499,
    originalPrice: 12499,
    discount: 0,
    rating: 4.7,
    reviewCount: 45,
    sku: "RA-MEH-AN12",
    stock: 8,
    images: ["./assets/images/anarkali_maroon.jpg", "./assets/images/anarkali_maroon_back.jpg"],
    colors: ["Maroon"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fabric: "Silk Velvet & Georgette",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 13,
    name: "Riwaayat Ivory Anarkali Set",
    slug: "riwaayat-ivory-anarkali-set",
    category: "Anarkali",
    subcategory: "Organza Suits",
    tags: ["ivory", "anarkali", "organza", "festive", "golden"],
    shortDescription: "Elegant ivory organza Anarkali with gold hand-blocked khadi borders.",
    fullDescription: "The Riwaayat Anarkali displays lightweight cotton-silk lining with a sheer ivory organza cover, detailed with gold khadi hand-block printed elements along the flare. Complete with churidar leggings.",
    price: 8999,
    originalPrice: 9999,
    discount: 10,
    rating: 4.7,
    reviewCount: 28,
    sku: "RA-RIW-AN13",
    stock: 12,
    images: ["./assets/images/anarkali_ivory.jpg", "./assets/images/anarkali_ivory_back.jpg"],
    colors: ["Ivory"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Organza & Cotton Silk",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 14,
    name: "Sage Green Bridal Anarkali Gown",
    slug: "sage-green-bridal-anarkali-gown",
    category: "Anarkali",
    subcategory: "Bridal Suits",
    tags: ["green", "sage", "bridal", "anarkali", "gown", "heavy embroidery"],
    shortDescription: "Sage green heavily embroidered bridal Anarkali gown with trail dupatta.",
    fullDescription: "An absolute showstopper for the bride-to-be. The Sage Green Anarkali Gown is crafted from sheer net and organza with hand-embroidered floral motifs across the full length, paired with wide-leg pants and a trail dupatta.",
    price: 18999,
    originalPrice: 21999,
    discount: 13,
    rating: 4.9,
    reviewCount: 12,
    sku: "RA-SAG-GN14",
    stock: 5,
    images: ["./assets/images/image copy 8.png", "./assets/images/image copy 8.png"],
    colors: ["Sage Green", "Mint"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Net & Organza",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 15,
    name: "Mustard Yellow Anarkali Suit",
    slug: "mustard-yellow-anarkali-suit",
    category: "Anarkali",
    subcategory: "Silk Suits",
    tags: ["mustard", "yellow", "anarkali", "festive", "colorful", "embroidered"],
    shortDescription: "Vibrant mustard Anarkali with Rajasthani gota work and printed dhoti pants.",
    fullDescription: "Celebrate with colour! The Mustard Yellow Anarkali features a flared A-line kameez in bright mustard with intricate gota patti and sequin floral borders, paired with printed dhoti-style pants and a matching dupatta.",
    price: 5999,
    originalPrice: 6799,
    discount: 11,
    rating: 4.6,
    reviewCount: 38,
    sku: "RA-MUS-AN15",
    stock: 18,
    images: ["./assets/images/image copy 12.png", "./assets/images/image copy 12.png"],
    colors: ["Mustard Yellow"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    fabric: "Silk & Net",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 16,
    name: "White Sequin Anarkali Gown",
    slug: "white-sequin-anarkali-gown",
    category: "Anarkali",
    subcategory: "Organza Suits",
    tags: ["white", "ivory", "anarkali", "sequin", "reception", "bridal"],
    shortDescription: "Ethereal white georgette Anarkali gown with all-over gold sequin embroidery.",
    fullDescription: "Pure and breathtaking, the White Sequin Anarkali is the perfect reception outfit. Crafted from soft georgette with all-over gold and silver sequin scattered embroidery, the full-length flowing gown comes with a matching sheer dupatta.",
    price: 13999,
    originalPrice: 15999,
    discount: 12,
    rating: 4.8,
    reviewCount: 23,
    sku: "RA-WHT-AN16",
    stock: 7,
    images: ["./assets/images/image copy 17.png", "./assets/images/image copy 17.png"],
    colors: ["White", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Georgette & Net",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: true
  },
  {
    id: 17,
    name: "Peach Floral Anarkali Set",
    slug: "peach-floral-anarkali-set",
    category: "Anarkali",
    subcategory: "Lawn",
    tags: ["peach", "floral", "anarkali", "summer", "printed", "casual"],
    shortDescription: "Romantic peach floral printed organza Anarkali with flared hem and chiffon dupatta.",
    fullDescription: "Fresh and feminine, the Peach Floral Anarkali features a delicate watercolour floral print across sheer organza. The flared hem, bishop sleeves, and matching printed dupatta make it a must-have for garden parties and summer events.",
    price: 4499,
    originalPrice: 4999,
    discount: 10,
    rating: 4.7,
    reviewCount: 34,
    sku: "RA-PCH-AN17",
    stock: 22,
    images: ["./assets/images/image copy 19.png", "./assets/images/image copy 19.png"],
    colors: ["Peach", "Pink"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Organza & Chiffon",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: true,
    newArrival: true
  },

  /* =========================================================
     CATEGORY: Sharara Set
  ========================================================= */
  {
    id: 18,
    name: "Gulnaar Plum Wedding Sharara Set",
    slug: "gulnaar-plum-wedding-sharara-set",
    category: "Sharara Set",
    subcategory: "Silk Suits",
    tags: ["plum", "sharara", "silk", "wedding", "zardozi"],
    shortDescription: "Glorious raw silk plum sharara embellished with gold zari and dabka embroidery.",
    fullDescription: "Exude sheer royalty in our Gulnaar Sharara Set. Tailored from premium raw silk in deep plum, the short kurta features detailed handcrafted Dabka and Zardozi borders, paired with a heavily flared layered sharara pant and a delicate tissue organza dupatta.",
    price: 11999,
    originalPrice: 12999,
    discount: 8,
    rating: 4.9,
    reviewCount: 38,
    sku: "RA-GUL-SH18",
    stock: 12,
    images: ["./assets/images/sharara_plum.jpg", "./assets/images/sharara_plum_back.jpg"],
    colors: ["Plum", "Deep Maroon"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Raw Silk & Organza",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 19,
    name: "Sage Green Sharara Suit Set",
    slug: "sage-green-sharara-suit-set",
    category: "Sharara Set",
    subcategory: "Silk Suits",
    tags: ["green", "sage", "sharara", "embroidered", "festive"],
    shortDescription: "Sage green silk sharara set with gold and pink thread embroidery and matching dupatta.",
    fullDescription: "The Sage Green Sharara Set is a perfect blend of modern aesthetics and traditional craftsmanship. Features a knee-length kameez in sage green organza with gold and pink floral thread work, paired with matching flared sharara pants.",
    price: 9999,
    originalPrice: 10999,
    discount: 9,
    rating: 4.8,
    reviewCount: 16,
    sku: "RA-SGR-SH19",
    stock: 14,
    images: ["./assets/images/image copy 11.png", "./assets/images/image copy 11.png"],
    colors: ["Sage Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
    fabric: "Organza & Silk",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 20,
    name: "Off-White Bridal Sharara Set",
    slug: "off-white-bridal-sharara-set",
    category: "Sharara Set",
    subcategory: "Pakistani Suits",
    tags: ["ivory", "white", "sharara", "bridal", "embroidered", "wedding"],
    shortDescription: "Off-white Pakistani bridal sharara set with heavy sequin and crystal embroidery.",
    fullDescription: "Illuminate every room in our Off-White Bridal Sharara. Heavily adorned with crystal, sequin, and thread embroidery, this three-piece set includes a fitted kameez, flared sharara and an embellished dupatta — perfect for the modern bride.",
    price: 14499,
    originalPrice: 15999,
    discount: 9,
    rating: 4.9,
    reviewCount: 20,
    sku: "RA-OWH-SH20",
    stock: 9,
    images: ["./assets/images/image copy 10.png", "./assets/images/image copy 10.png"],
    colors: ["Off-White", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Organza & Net",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 21,
    name: "Grey Mirror Work Sharara Set",
    slug: "grey-mirror-work-sharara-set",
    category: "Sharara Set",
    subcategory: "Georgette Suits",
    tags: ["grey", "mirror work", "sharara", "festive", "geometric"],
    shortDescription: "Steel grey georgette sharara with mirror and sequin embroidery and navy dupatta.",
    fullDescription: "A stunning pick for sangeets and mehndi ceremonies. The Grey Mirror Sharara features a flowing georgette kameez top with all-over hand-stitched sequin and mirror work, paired with matching wide-leg sharara pants and a navy dupatta.",
    price: 8499,
    originalPrice: 9499,
    discount: 10,
    rating: 4.6,
    reviewCount: 23,
    sku: "RA-GRY-SH21",
    stock: 11,
    images: ["./assets/images/image copy 15.png", "./assets/images/image copy 15.png"],
    colors: ["Grey", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Georgette",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: false,
    newArrival: true
  },

  /* =========================================================
     CATEGORY: Palazzo Suit
  ========================================================= */
  {
    id: 22,
    name: "Aafreen Organza Gold Palazzo Suit",
    slug: "aafreen-organza-gold-palazzo-suit",
    category: "Palazzo Suit",
    subcategory: "Organza Suits",
    tags: ["gold", "palazzo", "organza", "festive", "wide-leg"],
    shortDescription: "Elegant cream-gold organza kameez with wide flared georgette palazzos.",
    fullDescription: "Drape yourself in sheer luxury. The Aafreen Suit couples a sheer, hand-painted floral organza straight kameez with heavy flared palazzo pants. Trimmed with gold lace ribbons and accompanied by a sheer net dupatta.",
    price: 7999,
    originalPrice: 8999,
    discount: 11,
    rating: 4.8,
    reviewCount: 14,
    sku: "RA-AAF-OR22",
    stock: 15,
    images: ["./assets/images/palazzo_gold.jpg", "./assets/images/palazzo_gold_back.jpg"],
    colors: ["Muted Gold", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Luxury Organza & Georgette",
    occasion: "Wedding Couture",
    careInstructions: "Dry Clean Only",
    featured: true,
    bestseller: false,
    newArrival: true
  },
  {
    id: 23,
    name: "Zoya Yellow Palazzo Co-ord Set",
    slug: "zoya-yellow-palazzo-co-ord-set",
    category: "Palazzo Suit",
    subcategory: "Georgette Suits",
    tags: ["yellow", "palazzo", "co-ord", "printed", "modern", "summer"],
    shortDescription: "Vibrant yellow tie-dye printed asymmetric top with wide palazzo pants.",
    fullDescription: "Make a bold, modern statement with the Zoya Yellow Co-ord Set. Features a yellow marble-dye asymmetric kurti top with sequin border trim, paired with matching wide-leg palazzo pants. Perfect for beach events and modern celebrations.",
    price: 5499,
    originalPrice: 5999,
    discount: 8,
    rating: 4.6,
    reviewCount: 27,
    sku: "RA-ZOY-YL23",
    stock: 14,
    images: ["./assets/images/image copy 16.png", "./assets/images/image copy 16.png"],
    colors: ["Yellow", "Gold"],
    sizes: ["M", "L", "XL", "XXL"],
    fabric: "Georgette & Net",
    occasion: "Casual Luxury",
    careInstructions: "Gentle Hand Wash",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 24,
    name: "Yellow Lemon Palazzo Kurta Set",
    slug: "yellow-lemon-palazzo-kurta-set",
    category: "Palazzo Suit",
    subcategory: "Silk Suits",
    tags: ["yellow", "lemon", "palazzo", "silk", "casual", "summer"],
    shortDescription: "Soft lemon yellow silk kurta with gold Aari embroidery and matching dhoti pants.",
    fullDescription: "Bright, breezy and beautifully crafted, this lemon yellow silk kurta set features gold Aari neck embroidery with lace sleeves, paired with matching dhoti-style palazzo pants. Ideal for daytime festivities and Eid.",
    price: 4999,
    originalPrice: 5499,
    discount: 9,
    rating: 4.7,
    reviewCount: 18,
    sku: "RA-LMN-PL24",
    stock: 20,
    images: ["./assets/images/image copy 13.png", "./assets/images/image copy 13.png"],
    colors: ["Lemon Yellow"],
    sizes: ["S", "M", "L", "XL"],
    fabric: "Silk",
    occasion: "Festive Wear",
    careInstructions: "Dry Clean Only",
    featured: false,
    bestseller: false,
    newArrival: true
  }
];

// Helper functions for accessing product lists
function getProductById(id) {
  return products.find(p => p.id === parseInt(id)) || null;
}

function getProductBySlug(slug) {
  return products.find(p => p.slug === slug) || null;
}

function getFeaturedProducts() {
  return products.filter(p => p.featured === true);
}

function getBestsellers() {
  return products.filter(p => p.bestseller === true);
}

function getNewArrivals() {
  return products.filter(p => p.newArrival === true);
}

function getRelatedProducts(category, excludeId, limit = 4) {
  return products
    .filter(p => p.category === category && p.id !== parseInt(excludeId))
    .slice(0, limit);
}

function getProductsByCategory(category) {
  return products.filter(p => p.category === category);
}

function getProductsByTag(tag) {
  return products.filter(p => p.tags && p.tags.includes(tag.toLowerCase()));
}

function formatCurrency(amount) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(amount);
}
